--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/JonyGamesYT9/SimpleBroadcast
build-by-default: true
branches:
- main
projects:
  SimpleBroadcast:
    path: ""
    icon: "icon.png"
...
